const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const places=[{type:'city',name:'Bologna',country:'Italia',iata:'BLQ',airport:'Aeroporto Guglielmo Marconi di Bologna'},{type:'airport',name:'Aeroporto di Bologna',country:'Italia',iata:'BLQ',city:'Bologna'},{type:'city',name:'Milano',country:'Italia',iata:'MIL',airport:'Milano (tutti gli aeroporti)'},{type:'airport',name:'Milano Malpensa',country:'Italia',iata:'MXP',city:'Milano'},{type:'airport',name:'Milano Bergamo',country:'Italia',iata:'BGY',city:'Milano / Bergamo'},{type:'airport',name:'Milano Linate',country:'Italia',iata:'LIN',city:'Milano'},{type:'city',name:'Roma',country:'Italia',iata:'ROM',airport:'Roma (tutti gli aeroporti)'},{type:'airport',name:'Roma Fiumicino',country:'Italia',iata:'FCO',city:'Roma'},{type:'city',name:'Barcellona',country:'Spagna',iata:'BCN',airport:'Aeroporto Josep Tarradellas Barcelona-El Prat'},{type:'airport',name:'Barcellona El Prat',country:'Spagna',iata:'BCN',city:'Barcellona'},{type:'city',name:'Madrid',country:'Spagna',iata:'MAD',airport:'Adolfo Suárez Madrid-Barajas'},{type:'city',name:'Agadir',country:'Marocco',iata:'AGA',airport:'Aeroporto di Agadir-Al Massira'},{type:'city',name:'Marrakech',country:'Marocco',iata:'RAK',airport:'Aeroporto di Marrakech-Menara'},{type:'city',name:'Casablanca',country:'Marocco',iata:'CMN',airport:'Aeroporto Mohammed V'},{type:'country',name:'Marocco',country:'Marocco'},{type:'country',name:'Spagna',country:'Spagna'},{type:'country',name:'Italia',country:'Italia'}];
const airlines=['Ryanair','easyJet','Wizz Air','Vueling','Volotea','ITA Airways','Lufthansa','Air France','KLM','Iberia','British Airways','TAP Air Portugal','Turkish Airlines','Royal Air Maroc','Air Arabia Maroc','Transavia','Eurowings','SWISS','Austrian Airlines','Norwegian','Pegasus Airlines','Brussels Airlines'];
const countries=['Albania','Austria','Belgio','Bulgaria','Cipro','Croazia','Danimarca','Egitto','Emirati Arabi Uniti','Finlandia','Francia','Germania','Grecia','Irlanda','Islanda','Italia','Marocco','Malta','Norvegia','Paesi Bassi','Polonia','Portogallo','Qatar','Regno Unito','Repubblica Ceca','Romania','Serbia','Spagna','Svezia','Svizzera','Tunisia','Turchia','Ungheria'];
const state={trip:'roundtrip',mode:'flexible',origin:null,destination:null,anywhere:false,flexKinds:{out:'exact',in:'exact'},passengers:{adults:1,children:0,infantsSeat:0,infantsLap:0},airlineInclude:[],airlineExclude:[],avoidCountries:[]};
const typeLabels={city:'Città',airport:'Aeroporto',country:'Paese'},typeIcons={city:'●',airport:'✈',country:'◒'};
function init(){setDefaultDates();bind();renderPassengerRows();setFlexKind('out','exact');setFlexKind('in','exact');renderTags('include');renderTags('exclude');renderCountryTags();setTrip('roundtrip');setMode('flexible')}
function bind(){
 $$('.segment').forEach(b=>b.addEventListener('click',()=>setTrip(b.dataset.trip)));$$('.chip').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));bindLocation('origin','originSuggestions');bindLocation('destination','destinationSuggestions');$('#anywhereToggle').addEventListener('change',handleAnywhere);
 $('#swap').addEventListener('click',()=>{if(state.anywhere)return;const o=state.origin;state.origin=state.destination;state.destination=o;$('#origin').value=state.origin?.name||'';$('#destination').value=state.destination?.name||''});
 $$('[data-clear]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.clear;$('#'+id).value='';state[id]=null;$('#'+id+'Suggestions')?.classList.add('hidden')}));
 $$('[data-flex-kind]').forEach(b=>b.addEventListener('click',()=>setFlexKind(b.dataset.flexLeg,b.dataset.flexKind)));bindRange('flexOutFrom','flexOutTo');bindRange('flexInFrom','flexInTo');$('#nights').addEventListener('change',clampNights);$('#nights').addEventListener('blur',clampNights);
 $('#advancedToggle').addEventListener('click',()=>{const p=$('#advancedPanel'),h=p.classList.toggle('hidden');$('#advancedToggle').setAttribute('aria-expanded',String(!h));$('.advanced-entry-arrow').textContent=h?'›':'⌄'});
 bindAirlineInput('airlineIncludeInput','airlineIncludeSuggestions','include');bindAirlineInput('airlineExcludeInput','airlineExcludeSuggestions','exclude');bindCountryInput();
 $('#passengerButton').addEventListener('click',openPassengers);$('#closePassengers').addEventListener('click',closePassengers);$('#passengerDone').addEventListener('click',closePassengers);$('#sheetBackdrop').addEventListener('click',closePassengers);$('#searchButton').addEventListener('click',runSearch);$('#openHelp').addEventListener('click',()=>$('#helpModal').classList.remove('hidden'));$$('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>$('#helpModal').classList.add('hidden')));$('#helpModal').addEventListener('click',e=>{if(e.target.id==='helpModal')e.currentTarget.classList.add('hidden')});
 document.addEventListener('click',e=>{if(!e.target.closest('.location-field'))$$('.suggestions').forEach(x=>x.classList.add('hidden'));if(!e.target.closest('.tag-input-wrap'))$$('.smart-suggestions').forEach(x=>x.classList.add('hidden'))})
}
function setDefaultDates(){const t=new Date(),d=addDays(t,7),r=addDays(d,3),v={flexOutExact:d,flexOutBase:d,flexOutFrom:d,flexOutTo:addDays(d,10),flexInExact:r,flexInBase:r,flexInFrom:r,flexInTo:addDays(r,10)};Object.entries(v).forEach(([id,date])=>{$('#'+id).value=dateInput(date);$('#'+id).min=dateInput(t)})}
function setTrip(v){state.trip=v;$$('.segment').forEach(b=>b.classList.toggle('active',b.dataset.trip===v));const one=v==='oneway';$$('.return-control').forEach(x=>x.classList.toggle('hidden',one));$$('.roundtrip-only').forEach(x=>x.classList.toggle('hidden',one));$$('.roundtrip-date-mode').forEach(x=>x.classList.toggle('hidden',one));$('#flexibleIntro').textContent=one?'Scegli una data precisa, una data con tolleranza di alcuni giorni oppure un intervallo.':'Andata e ritorno possono avere regole diverse: data precisa, tolleranza di alcuni giorni oppure intervallo.';if(one&&state.mode!=='flexible')setMode('flexible')}
function setMode(v){if(state.trip==='oneway'&&v!=='flexible')v='flexible';state.mode=v;$$('.chip').forEach(b=>b.classList.toggle('active',b.dataset.mode===v));['flexible','cheapest','weekend'].forEach(m=>$('#'+m+'Panel').classList.toggle('hidden',m!==v))}
function setFlexKind(leg,kind){state.flexKinds[leg]=kind;$$(`[data-flex-leg="${leg}"]`).forEach(b=>b.classList.toggle('active',b.dataset.flexKind===kind));['exact','plusminus','range'].forEach(k=>$(`[data-flex-panel="${leg}-${k}"]`).classList.toggle('hidden',k!==kind))}
function handleAnywhere(){const c=$('#anywhereToggle').checked;state.anywhere=c;state.destination=c?{type:'anywhere',name:'Ovunque'}:null;const i=$('#destination');i.disabled=c;$('[data-clear="destination"]').disabled=c;$('#destinationWrap').classList.toggle('disabled',c);$('#swap').disabled=c;$('#swap').classList.toggle('disabled',c);$('#destinationSuggestions').classList.add('hidden');i.value=c?'Ovunque':''}
function bindLocation(id,sid){const input=$('#'+id),box=$('#'+sid);const update=()=>{state[id]=null;const q=norm(input.value);if(!q)return box.classList.add('hidden');const m=places.filter(p=>norm([p.name,p.country,p.iata,p.airport,p.city].filter(Boolean).join(' ')).includes(q)).slice(0,8);box.innerHTML=m.length?m.map((p,i)=>`<button class="suggestion" type="button" data-i="${i}"><span class="type-icon">${typeIcons[p.type]}</span><span><strong>${esc(p.name)}${p.iata?` · ${esc(p.iata)}`:''}</strong><small>${typeLabels[p.type]}${p.country?` · ${esc(p.country)}`:''}${p.airport&&p.type==='city'?` · ${esc(p.airport)}`:''}</small></span></button>`).join(''):'<div class="suggestion empty-suggestion"><span><strong>Nessun suggerimento locale</strong><small>Il dataset globale verrà ampliato insieme alla sorgente voli reale.</small></span></div>';box.classList.remove('hidden');$$('.suggestion[data-i]',box).forEach(b=>b.addEventListener('click',()=>{const p=m[Number(b.dataset.i)];state[id]=p;input.value=p.name;box.classList.add('hidden')}))};input.addEventListener('input',update);input.addEventListener('focus',update)}
function bindRange(a,b){const f=$('#'+a),t=$('#'+b);f.addEventListener('change',()=>{t.min=f.value;if(t.value&&t.value<f.value)t.value=f.value})}
function clampNights(){const i=$('#nights');let v=parseInt(i.value,10);if(!Number.isFinite(v))v=1;i.value=String(Math.min(15,Math.max(1,v)))}
function bindAirlineInput(inputId,sid,key){const input=$('#'+inputId),s=$('#'+sid);const update=()=>{const q=norm(input.value),sel=key==='include'?state.airlineInclude:state.airlineExclude,m=airlines.filter(n=>(!q||norm(n).includes(q))&&!sel.includes(n)).slice(0,8);s.innerHTML=m.length?m.map((n,i)=>`<button type="button" data-smart-i="${i}">${esc(n)}</button>`).join(''):'<div class="suggestion-empty">Nessuna compagnia trovata</div>';s.classList.remove('hidden');$$('[data-smart-i]',s).forEach(b=>b.addEventListener('click',()=>{addAirline(key,m[Number(b.dataset.smartI)]);input.value='';s.classList.add('hidden')}));return m};input.addEventListener('input',update);input.addEventListener('focus',update);input.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const m=update();if(!m.length)return;e.preventDefault();addAirline(key,m[0]);input.value='';s.classList.add('hidden')})}
function addAirline(key,name){const t=key==='include'?state.airlineInclude:state.airlineExclude,o=key==='include'?state.airlineExclude:state.airlineInclude;if(!t.includes(name))t.push(name);const c=o.indexOf(name);if(c>=0)o.splice(c,1);renderTags('include');renderTags('exclude')}
function renderTags(key){const l=key==='include'?state.airlineInclude:state.airlineExclude,c=$('#'+(key==='include'?'airlineIncludeChips':'airlineExcludeChips'));c.innerHTML=l.map((n,i)=>`<span class="tag"><span>${esc(n)}</span><button type="button" data-remove-tag="${key}" data-index="${i}" aria-label="Rimuovi ${esc(n)}">×</button></span>`).join('');$$('[data-remove-tag]',c).forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.removeTag==='include'?state.airlineInclude:state.airlineExclude;t.splice(Number(b.dataset.index),1);renderTags(b.dataset.removeTag)}))}
function bindCountryInput(){const input=$('#avoidCountriesInput'),s=$('#avoidCountrySuggestions');const update=()=>{const q=norm(input.value),m=countries.filter(n=>(!q||norm(n).includes(q))&&!state.avoidCountries.includes(n)).slice(0,8);s.innerHTML=m.length?m.map((n,i)=>`<button type="button" data-country-i="${i}">${esc(n)}</button>`).join(''):'<div class="suggestion-empty">Nessun Paese trovato</div>';s.classList.remove('hidden');$$('[data-country-i]',s).forEach(b=>b.addEventListener('click',()=>{addCountry(m[Number(b.dataset.countryI)]);input.value='';s.classList.add('hidden')}));return m};input.addEventListener('input',update);input.addEventListener('focus',update);input.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const m=update();if(!m.length)return;e.preventDefault();addCountry(m[0]);input.value='';s.classList.add('hidden')})}
function addCountry(n){if(!state.avoidCountries.includes(n))state.avoidCountries.push(n);renderCountryTags()}
function renderCountryTags(){const c=$('#avoidCountryChips');c.innerHTML=state.avoidCountries.map((n,i)=>`<span class="tag"><span>${esc(n)}</span><button type="button" data-remove-country="${i}" aria-label="Rimuovi ${esc(n)}">×</button></span>`).join('');$$('[data-remove-country]',c).forEach(b=>b.addEventListener('click',()=>{state.avoidCountries.splice(Number(b.dataset.removeCountry),1);renderCountryTags()}))}
function openPassengers(){$('#sheetBackdrop').classList.remove('hidden');$('#passengerSheet').classList.remove('hidden')}function closePassengers(){$('#sheetBackdrop').classList.add('hidden');$('#passengerSheet').classList.add('hidden');updatePassengerSummary()}
function renderPassengerRows(){const rows=[['adults','Adulti','12+ anni'],['children','Bambini','2–11 anni'],['infantsSeat','Neonati con posto','Meno di 2 anni'],['infantsLap','Neonati in braccio','Meno di 2 anni']];$('#passengerRows').innerHTML=rows.map(([k,l,s])=>`<div class="counter-row"><div><strong>${l}</strong><small>${s}</small></div><div class="counter"><button type="button" data-k="${k}" data-d="-1">−</button><strong id="count-${k}">${state.passengers[k]}</strong><button type="button" data-k="${k}" data-d="1">+</button></div></div>`).join('');$$('.counter button').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.k,min=k==='adults'?1:0;state.passengers[k]=Math.max(min,state.passengers[k]+Number(b.dataset.d));$('#count-'+k).textContent=state.passengers[k]}))}
function updatePassengerSummary(){const p=state.passengers,t=p.adults+p.children+p.infantsSeat+p.infantsLap;$('#passengerSummary').textContent=t===1?'1 adulto':`${t} passeggeri`}
function runSearch(){const o=state.origin||findTyped($('#origin').value),d=state.anywhere?{type:'anywhere',name:'Ovunque'}:(state.destination||findTyped($('#destination').value));if(!o||!d)return showResult('Manca una località','Scegli partenza e destinazione dai suggerimenti per evitare ambiguità.');if(o.name===d.name)return showResult('Controlla la rotta','Partenza e destinazione devono essere diverse.');const detail=[];if(state.mode==='flexible'){detail.push(`Andata: ${getFlexSummary('out')}`);if(state.trip==='roundtrip')detail.push(`Ritorno: ${getFlexSummary('in')}`)}else if(state.mode==='cheapest'){clampNights();detail.push(`${$('#nights').value} notti · entro ${$('#horizon').selectedOptions[0].textContent}`)}else detail.push(`${$('#weekendOut').value} dopo le ${$('#weekendOutTime').value} · ritorno ${$('#weekendBack').value.toLowerCase()} verso le ${$('#weekendBackTime').value}`);detail.push($('#stops').selectedOptions[0].textContent,$('#passengerSummary').textContent);const strat=state.trip==='roundtrip'?document.querySelector('input[name="airlineStrategy"]:checked')?.value:'any';if(strat==='same')detail.push('Stessa compagnia per A/R');if(strat==='different')detail.push('Compagnie diverse tra A/R');if(state.airlineInclude.length)detail.push(`Preferite: ${state.airlineInclude.join(', ')}`);if(state.airlineExclude.length)detail.push(`Escluse: ${state.airlineExclude.join(', ')}`);if(state.avoidCountries.length)detail.push(`No scali: ${state.avoidCountries.join(', ')}`);$('#resultTitle').textContent=`${o.name} → ${d.name}`;const note=d.type==='country'?`Prima di mostrare voli, Fly2 dovrà individuare le città realmente raggiungibili in ${esc(d.name)} nelle condizioni selezionate.`:d.type==='anywhere'?'Con “Ovunque”, Fly2 confronterà soltanto destinazioni realmente disponibili quando sarà collegata la sorgente dati.':'';$('#resultContent').innerHTML=`<article class="result-card"><div class="summary-route"><div><strong>${esc(o.name)} → ${esc(d.name)}</strong><span>${state.trip==='roundtrip'?'Andata e ritorno':'Solo andata'} · ${labelMode(state.mode)}</span></div><span>${o.iata||''}${o.iata&&d.iata?' → ':''}${d.iata||''}</span></div><div class="selection-list">${detail.map(x=>`<span>${esc(x)}</span>`).join('')}</div>${note?`<div class="notice">${note}</div>`:''}<div class="notice"><strong>Nessun prezzo mostrato.</strong><br>La configurazione della ricerca è pronta, ma Fly2 non è ancora collegata a una sorgente gratuita affidabile per prezzi e disponibilità reali.</div></article>`;$('#resultSortWrap').classList.add('hidden');$('#resultSection').classList.remove('hidden');$('#resultSection').scrollIntoView({behavior:'smooth',block:'start'})}
function getFlexSummary(leg){const k=state.flexKinds[leg],p=leg==='out'?'flexOut':'flexIn';if(k==='exact')return prettyDate($('#'+p+'Exact').value);if(k==='plusminus')return `${prettyDate($('#'+p+'Base').value)} ± ${$('#'+p+'Days').value} giorni`;return `${prettyDate($('#'+p+'From').value)} – ${prettyDate($('#'+p+'To').value)}`}
function showResult(t,m){$('#resultTitle').textContent=t;$('#resultContent').innerHTML=`<article class="result-card"><div class="notice">${esc(m)}</div></article>`;$('#resultSortWrap').classList.add('hidden');$('#resultSection').classList.remove('hidden');$('#resultSection').scrollIntoView({behavior:'smooth',block:'start'})}
function findTyped(v){const q=norm(v);return places.find(p=>norm(p.name)===q||norm(p.iata||'')===q)||null}function labelMode(m){return m==='flexible'?'Date flessibili':m==='cheapest'?'Periodo più economico':'Weekend'}function addDays(d,n){const r=new Date(d);r.setDate(r.getDate()+n);return r}function dateInput(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function prettyDate(v){if(!v)return'non scelta';return new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v+'T12:00:00'))}function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
init();
